version: '3.8'

services:
  backend:
    build: .
    ports:
      -  "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=test_db;Username=postgres;Password=yourpassword
    depends_on:
      - postgres
    entrypoint: ["sh", "-c", "dotnet test-backend.dll && dotnet ef database update"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
