name: .NET Application Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Publish .NET Application
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.publish.outputs.artifact-path }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build project
      run: dotnet build test-backend.csproj --configuration Release

    - name: Publish project
      id: publish
      run: |
        dotnet publish test-backend.csproj -c Release -o ./publish
        echo "::set-output name=artifact-path::$(pwd)/publish"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: ${{ steps.publish.outputs.artifact-path }}

  deploy:
    name: Deploy Application
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: published-app
        path: deploy
    
    - name: create directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: | 
          if [ ! -d "/home/azureuser/app" ]; then
            mkdir -p /home/azureuser/app;
            sudo chown azureuser:azureuser /home/azureuser/app;
          fi
    - name: Copy files to the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "deploy/*"
        target: "/home/azureuser/app"

  run-migrations-and-restart:
    name: Run Migrations and Restart Server
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Run Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/azureuser/app
          dotnet restore
          dotnet ef database update
